version: '3.8'

services:
  api-pki:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-pki
    ports:
      - "8081:8081"
    volumes:
      - ./simplepki:/app/simplepki
    restart: always
    networks:
      - unbsign-webapp_unbsign-network

networks:
  unbsign-webapp_unbsign-network:
    external: true